name: Build Android App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Step 3: Install Buildozer and Dependencies
      - name: Install Buildozer
        run: |
          pip install --upgrade pip setuptools wheel
          pip install buildozer

      # Step 4: Clean the Buildozer Environment
      - name: Buildozer Clean
        run: |
          buildozer android clean
